name: build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'

      - name: install additional native dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang lldb lld libldap2-dev libidn2-dev curl libcurl4-openssl-dev libstdc++-12-dev libgc-dev libssl-dev
          version: 1.0

      - name: build
        run: |
          export SBT_OPTS="-Xmx6G -Xss5M"
          sbt clean build-all

      - name: create graalvm upload.zip
        run: |
          zip upload.zip dist/bootstrap modules/graalvm-native-service/target/graalvm-native-image/scala-native-aws-lambda-graalvm-native-service

      - name: upload graalvm binary
        uses: actions/upload-artifact@v3
        with:
          name: graalvm-native-service
          path: modules/graalvm-native-service/target/graalvm-native-image/
          retention-days: 14

      - name: upload graalvm upload.zip
        uses: actions/upload-artifact@v3
        with:
          name: upload.zip
          path: upload.zip
          retention-days: 14

      - name: upload scala native binary
        uses: actions/upload-artifact@v3
        with:
          name: scala-native-service
          path: modules/scala-native-service/target/scala-2.13/scala-native-aws-lambda-scala-native-service-out
          retention-days: 14
